"""add book analysis fields

Revision ID: 180101791802
Revises: b2dc76e73cae
Create Date: 2026-09-10 23:19:53.689493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '180101791802'
down_revision: Union[str, Sequence[str], None] = 'b2dc76e73cae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('themes', sa.JSON(), nullable=True))
    op.add_column('books', sa.Column('atmosphere', sa.JSON(), nullable=True))
    op.add_column('books', sa.Column('story_elements', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'story_elements')
    op.drop_column('books', 'atmosphere')
    op.drop_column('books', 'themes')
    # ### end Alembic commands ###
